# Generated by Django 4.2.4 on 2023-10-12 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_delivery_delivery_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=15, null=True)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=15, null=True)),
                ('customer_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customeraddress')),
            ],
        ),
    ]
